export const browserCoreExamples = [
  "ironcliw browser status",
  "ironcliw browser start",
  "ironcliw browser stop",
  "ironcliw browser tabs",
  "ironcliw browser open https://example.com",
  "ironcliw browser focus abcd1234",
  "ironcliw browser close abcd1234",
  "ironcliw browser screenshot",
  "ironcliw browser screenshot --full-page",
  "ironcliw browser screenshot --ref 12",
  "ironcliw browser snapshot",
  "ironcliw browser snapshot --format aria --limit 200",
  "ironcliw browser snapshot --efficient",
  "ironcliw browser snapshot --labels",
];

export const browserActionExamples = [
  "ironcliw browser navigate https://example.com",
  "ironcliw browser resize 1280 720",
  "ironcliw browser click 12 --double",
  'ironcliw browser type 23 "hello" --submit',
  "ironcliw browser press Enter",
  "ironcliw browser hover 44",
  "ironcliw browser drag 10 11",
  "ironcliw browser select 9 OptionA OptionB",
  "ironcliw browser upload /tmp/ironcliw/uploads/file.pdf",
  'ironcliw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "ironcliw browser dialog --accept",
  'ironcliw browser wait --text "Done"',
  "ironcliw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "ironcliw browser console --level error",
  "ironcliw browser pdf",
];
