export const browserCoreExamples = [
  "Ironcliw browser status",
  "Ironcliw browser start",
  "Ironcliw browser stop",
  "Ironcliw browser tabs",
  "Ironcliw browser open https://example.com",
  "Ironcliw browser focus abcd1234",
  "Ironcliw browser close abcd1234",
  "Ironcliw browser screenshot",
  "Ironcliw browser screenshot --full-page",
  "Ironcliw browser screenshot --ref 12",
  "Ironcliw browser snapshot",
  "Ironcliw browser snapshot --format aria --limit 200",
  "Ironcliw browser snapshot --efficient",
  "Ironcliw browser snapshot --labels",
];

export const browserActionExamples = [
  "Ironcliw browser navigate https://example.com",
  "Ironcliw browser resize 1280 720",
  "Ironcliw browser click 12 --double",
  'Ironcliw browser type 23 "hello" --submit',
  "Ironcliw browser press Enter",
  "Ironcliw browser hover 44",
  "Ironcliw browser drag 10 11",
  "Ironcliw browser select 9 OptionA OptionB",
  "Ironcliw browser upload /tmp/Ironcliw/uploads/file.pdf",
  'Ironcliw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "Ironcliw browser dialog --accept",
  'Ironcliw browser wait --text "Done"',
  "Ironcliw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "Ironcliw browser console --level error",
  "Ironcliw browser pdf",
];

