export const browserCoreExamples = [
  "IronCliw browser status",
  "IronCliw browser start",
  "IronCliw browser stop",
  "IronCliw browser tabs",
  "IronCliw browser open https://example.com",
  "IronCliw browser focus abcd1234",
  "IronCliw browser close abcd1234",
  "IronCliw browser screenshot",
  "IronCliw browser screenshot --full-page",
  "IronCliw browser screenshot --ref 12",
  "IronCliw browser snapshot",
  "IronCliw browser snapshot --format aria --limit 200",
  "IronCliw browser snapshot --efficient",
  "IronCliw browser snapshot --labels",
];

export const browserActionExamples = [
  "IronCliw browser navigate https://example.com",
  "IronCliw browser resize 1280 720",
  "IronCliw browser click 12 --double",
  'IronCliw browser type 23 "hello" --submit',
  "IronCliw browser press Enter",
  "IronCliw browser hover 44",
  "IronCliw browser drag 10 11",
  "IronCliw browser select 9 OptionA OptionB",
  "IronCliw browser upload /tmp/IronCliw/uploads/file.pdf",
  'IronCliw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "IronCliw browser dialog --accept",
  'IronCliw browser wait --text "Done"',
  "IronCliw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "IronCliw browser console --level error",
  "IronCliw browser pdf",
];

